### PR TITLE
Sprint-Challenge--Intro-Python

### PR DESCRIPTION
**Pull request by vebradev**
Sorry @openwell, can't attempt stretch challenge. Every other test passes, so I think I'm in the MVP zone.

### CODE REVIEW

**Comment by vebradev** [comment]
So, submitted my work with around ~1hr remaining of my time, took my dog for a walk and tried to attempt stretch challenge afterwards. Had to go through few threads in the help channel because I initially didn't understand what I'm being asked to do and managed to get it working - tests are passing! Haven't looked at anyone's submissions and feeling pretty brain-strong this morning. 

Feel free not to count this towards my final submission, since it's way after the Sprint Challenge time. Just wanted to do this one, because not doing it is worse than trying. 💪

**Comment by openwell** [comment]
> Sorry @openwell, can't attempt stretch challenge. Every other test passes, so I think I'm in the MVP zone.

**Review by openwell — APPROVED** [review]
Great Job this week. Congratulations on the MVP and your attempt on the Stretch Goal. 
You can merge when all your stretch tests pass.

**Comment by vebradev** [comment]
> Great Job this week. Congratulations on the MVP and your attempt on the Stretch Goal.
> You can merge when all your stretch tests pass.

All tests are passing since Friday. Merging now. 🎉

**Pull request merged**
